"""add athlete_id to guardian_profiles

Revision ID: ecc34bc4d96a
Revises: 001
Create Date: 2026-06-27 00:07:38.312390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecc34bc4d96a'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardian_profiles', sa.Column('athlete_id', sa.UUID(), nullable=True))

    op.alter_column('athlete_profiles', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('athlete_profiles', 'profile_completion',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('athlete_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('athlete_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_athlete_profiles_user_id', 'athlete_profiles', type_='unique')
    op.drop_index('ix_athlete_profiles_user_id', table_name='athlete_profiles')
    op.create_index(op.f('ix_athlete_profiles_user_id'), 'athlete_profiles', ['user_id'], unique=True)
    op.alter_column('chat_messages', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chat_messages', 'moderation_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chat_messages', 'guardian_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chat_messages', 'is_system_message',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_threads', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chat_threads', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chat_threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_threads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_chat_threads_athlete_mentor', 'chat_threads', type_='unique')
    op.alter_column('colleges', 'sports_quota',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('colleges', 'hostel',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('colleges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('colleges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('guardian_profiles', 'athlete_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('guardian_profiles', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('guardian_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('guardian_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_guardian_profiles_user_id', 'guardian_profiles', type_='unique')
    op.create_index(op.f('ix_guardian_profiles_athlete_id'), 'guardian_profiles', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_guardian_profiles_user_id'), 'guardian_profiles', ['user_id'], unique=True)
    op.create_foreign_key(op.f('fk_guardian_profiles_athlete_id_athlete_profiles'), 'guardian_profiles', 'athlete_profiles', ['athlete_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('mentor_profiles', 'trust_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('mentor_profiles', 'total_reviews',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mentor_profiles', 'average_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('mentor_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mentor_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_mentor_profiles_user_id', 'mentor_profiles', type_='unique')
    op.drop_index('ix_mentor_profiles_user_id', table_name='mentor_profiles')
    op.create_index(op.f('ix_mentor_profiles_user_id'), 'mentor_profiles', ['user_id'], unique=True)
    op.alter_column('mentor_reviews', 'private_safety_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mentor_reviews', 'moderated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mentor_reviews', 'visible',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mentor_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mentor_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_mentor_reviews_mentor_athlete', 'mentor_reviews', type_='unique')
    op.alter_column('mentorship_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PENDING_GUARDIAN', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='requeststatus'),
               nullable=False)
    op.alter_column('mentorship_requests', 'mode',
               existing_type=postgresql.ENUM('ONLINE', 'OFFLINE', 'GROUP', 'CAREER_GUIDANCE', 'TRIAL_PREP', 'SCHOLARSHIP_GUIDANCE', name='mentorshipmode'),
               nullable=False)
    op.alter_column('mentorship_requests', 'guardian_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mentorship_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mentorship_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_mentorship_requests_guardian_id'), 'mentorship_requests', ['guardian_id'], unique=False)
    op.add_column('notifications', sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('notifications', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('notifications', 'metadata')
    op.alter_column('opportunities', 'women_focused',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('opportunities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('opportunities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_opportunities_deadline'), 'opportunities', ['deadline'], unique=False)
    op.alter_column('report_timeline', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('safety_reports', 'severity',
               existing_type=postgresql.ENUM('NORMAL', 'URGENT', 'EMERGENCY', name='reportseverity'),
               nullable=False)
    op.alter_column('safety_reports', 'anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('safety_reports', 'status',
               existing_type=postgresql.ENUM('SUBMITTED', 'UNDER_REVIEW', 'ESCALATED', 'RESOLVED', 'DISMISSED', name='reportstatus'),
               nullable=False)
    op.alter_column('safety_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('safety_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_safety_reports_ticket_id', 'safety_reports', type_='unique')
    op.drop_index('ix_safety_reports_ticket_id', table_name='safety_reports')
    op.create_index(op.f('ix_safety_reports_ticket_id'), 'safety_reports', ['ticket_id'], unique=True)
    op.create_index(op.f('ix_safety_reports_assigned_to'), 'safety_reports', ['assigned_to'], unique=False)
    op.alter_column('saved_scholarships', 'status',
               existing_type=postgresql.ENUM('SAVED', 'APPLYING', 'SUBMITTED', 'SHORTLISTED', 'APPROVED', 'REJECTED', name='savedstatus'),
               nullable=False)
    op.alter_column('saved_scholarships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_scholarships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_saved_scholarships_user_scholarship', 'saved_scholarships', type_='unique')
    op.alter_column('scholarships', 'girls_only',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('scholarships', 'hostel_support',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('scholarships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scholarships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sponsor_programs', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', 'UNDER_REVIEW', 'AWARDED', name='sponsorstatus'),
               nullable=False)
    op.alter_column('sponsor_programs', 'current_recipients',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sponsor_programs', 'women_focused',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sponsor_programs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sponsor_programs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_resources', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('training_resources', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('training_resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_constraint('uq_users_phone_number', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_phone_number', table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_phone_number', 'users', ['phone_number'])
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_resources', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('training_resources', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sponsor_programs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sponsor_programs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sponsor_programs', 'women_focused',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sponsor_programs', 'current_recipients',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sponsor_programs', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', 'UNDER_REVIEW', 'AWARDED', name='sponsorstatus'),
               nullable=True)
    op.alter_column('scholarships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scholarships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scholarships', 'hostel_support',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('scholarships', 'girls_only',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint('uq_saved_scholarships_user_scholarship', 'saved_scholarships', ['user_id', 'scholarship_id'])
    op.alter_column('saved_scholarships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_scholarships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_scholarships', 'status',
               existing_type=postgresql.ENUM('SAVED', 'APPLYING', 'SUBMITTED', 'SHORTLISTED', 'APPROVED', 'REJECTED', name='savedstatus'),
               nullable=True)
    op.drop_index(op.f('ix_safety_reports_assigned_to'), table_name='safety_reports')
    op.drop_index(op.f('ix_safety_reports_ticket_id'), table_name='safety_reports')
    op.create_index('ix_safety_reports_ticket_id', 'safety_reports', ['ticket_id'], unique=False)
    op.create_unique_constraint('uq_safety_reports_ticket_id', 'safety_reports', ['ticket_id'])
    op.alter_column('safety_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('safety_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('safety_reports', 'status',
               existing_type=postgresql.ENUM('SUBMITTED', 'UNDER_REVIEW', 'ESCALATED', 'RESOLVED', 'DISMISSED', name='reportstatus'),
               nullable=True)
    op.alter_column('safety_reports', 'anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('safety_reports', 'severity',
               existing_type=postgresql.ENUM('NORMAL', 'URGENT', 'EMERGENCY', name='reportseverity'),
               nullable=True)
    op.alter_column('report_timeline', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_opportunities_deadline'), table_name='opportunities')
    op.alter_column('opportunities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('opportunities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('opportunities', 'women_focused',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('notifications', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('notifications', 'extra_data')
    op.drop_index(op.f('ix_mentorship_requests_guardian_id'), table_name='mentorship_requests')
    op.alter_column('mentorship_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mentorship_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mentorship_requests', 'guardian_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mentorship_requests', 'mode',
               existing_type=postgresql.ENUM('ONLINE', 'OFFLINE', 'GROUP', 'CAREER_GUIDANCE', 'TRIAL_PREP', 'SCHOLARSHIP_GUIDANCE', name='mentorshipmode'),
               nullable=True)
    op.alter_column('mentorship_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PENDING_GUARDIAN', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='requeststatus'),
               nullable=True)
    op.create_unique_constraint('uq_mentor_reviews_mentor_athlete', 'mentor_reviews', ['mentor_id', 'athlete_id'])
    op.alter_column('mentor_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mentor_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mentor_reviews', 'visible',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mentor_reviews', 'moderated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mentor_reviews', 'private_safety_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_mentor_profiles_user_id'), table_name='mentor_profiles')
    op.create_index('ix_mentor_profiles_user_id', 'mentor_profiles', ['user_id'], unique=False)
    op.create_unique_constraint('uq_mentor_profiles_user_id', 'mentor_profiles', ['user_id'])
    op.alter_column('mentor_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mentor_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mentor_profiles', 'average_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('mentor_profiles', 'total_reviews',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mentor_profiles', 'trust_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('fk_guardian_profiles_athlete_id_athlete_profiles'), 'guardian_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_guardian_profiles_user_id'), table_name='guardian_profiles')
    op.drop_index(op.f('ix_guardian_profiles_athlete_id'), table_name='guardian_profiles')
    op.create_unique_constraint('uq_guardian_profiles_user_id', 'guardian_profiles', ['user_id'])
    op.alter_column('guardian_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('guardian_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('guardian_profiles', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('guardian_profiles', 'athlete_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('colleges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('colleges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('colleges', 'hostel',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('colleges', 'sports_quota',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint('uq_chat_threads_athlete_mentor', 'chat_threads', ['athlete_id', 'mentor_id'])
    op.alter_column('chat_threads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_threads', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chat_threads', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'is_system_message',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chat_messages', 'guardian_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chat_messages', 'moderation_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chat_messages', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_athlete_profiles_user_id'), table_name='athlete_profiles')
    op.create_index('ix_athlete_profiles_user_id', 'athlete_profiles', ['user_id'], unique=False)
    op.create_unique_constraint('uq_athlete_profiles_user_id', 'athlete_profiles', ['user_id'])
    op.alter_column('athlete_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('athlete_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('athlete_profiles', 'profile_completion',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('athlete_profiles', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='playing_with_neon_pkey')
    )
    # ### end Alembic commands ###
