/*
# SHAKTHI Platform - Seed Data

## Overview
Populates the database with realistic Indian sports data including:
- Sample athletes from various states
- Verified mentors with different expertise
- Sports scholarships for girls
- Colleges with sports quotas
- Upcoming opportunities (tournaments, trials, camps)
- Training resources
- Success stories

## Data Added
1. Scholarships - 8 scholarships specifically for girl athletes
2. Colleges - 10 universities with sports quotas
3. Opportunities - 12 upcoming events and programs
4. Training Resources - 15 educational resources
*/

-- Insert Scholarships
INSERT INTO scholarships (name, provider, amount, eligibility, deadline, state, sport, girls_only, hostel_support, application_mode, description, application_url, required_level, min_age, max_age) VALUES
('Khelo India Girls Sports Scholarship', 'Ministry of Youth Affairs & Sports', 500000, 'Indian female athletes aged 10-18 with state/national level achievement', '2026-03-31', NULL, NULL, true, true, 'Online', 'Comprehensive scholarship covering training, equipment, nutrition, and education support for talented girl athletes. Includes mentorship from national coaches.', 'https://kheloindia.gov.in/girls-scholarship', 'STATE', 10, 18),
('State Sports Talent Search Scholarship', 'Haryana Sports Department', 200000, 'Haryana resident female athletes with district level achievement', '2026-04-15', 'Haryana', NULL, true, true, 'Offline', 'Financial support for training and competition expenses. Preference to athletics, wrestling, boxing, and kabaddi.', 'https://haryanasports.gov.in/talent-search', 'DISTRICT', 12, 25),
('Rural Sports Foundation Scholarship', 'Rural Sports Foundation', 150000, 'Rural background female athletes with potential', '2026-02-28', NULL, NULL, true, false, 'Online', 'Supporting rural girl athletes with talent but limited resources. Includes training at partner academies.', 'https://ruralsportsfoundation.org/apply', 'SCHOOL', 8, 18),
('Women in Sports Excellence Award', 'Sports Authority of India', 300000, 'Female athletes representing India internationally', '2026-05-30', NULL, NULL, true, true, 'Online', 'Prestigious scholarship for international level women athletes. Covers international training exposure.', 'https://sportsauthorityofindia.gov.in/women-excellence', 'INTERNATIONAL', 16, 28),
('BCCI Women''s Cricket Scholarship', 'Board of Control for Cricket in India', 400000, 'Female cricketers under 23', '2026-06-30', NULL, 'Cricket', true, true, 'Online', 'Dedicated cricket scholarship for women including coaching at NCA, equipment, and match exposure.', 'https://bcci.tv/womens-scholarship', 'STATE', 14, 23),
('Badminton Association Women''s Grant', 'Badminton Association of India', 250000, 'Female badminton players at state level', '2026-04-30', NULL, 'Badminton', true, false, 'Online', 'Training support for aspiring female badminton players. Includes access to top academies.', 'https://badminmintonindia.org/womens-grant', 'STATE', 12, 22),
('Maharashtra Krida Puraskar', 'Maharashtra Sports Ministry', 175000, 'Maharashtra female athletes with state achievement', '2026-03-15', 'Maharashtra', NULL, true, true, 'Offline', 'State government scholarship for women athletes. Covers education and training expenses.', 'https://maharashtrasports.gov.in/krida-puraskar', 'STATE', 10, 21),
('Odisha Sports Excellence Scholarship', 'Sports Department Odisha', 180000, 'Odisha residents with sports achievements', '2026-05-15', 'Odisha', NULL, true, true, 'Online', 'Scholarship for athletes in hockey, athletics, and indigenous sports. Includes hostel facility.', 'https://odishasports.gov.in/excellence-scholarship', 'DISTRICT', 11, 22);

-- Insert Colleges with Sports Quota
INSERT INTO colleges (name, location, state, sports_quota, fee_concession, hostel, supported_sports, quota_rules, required_achievement_level, academic_streams, last_date, website_url, contact_email, contact_phone) VALUES
('Delhi University Sports College', 'New Delhi', 'Delhi', true, 50, true, ARRAY['Athletics', 'Cricket', 'Badminton', 'Table Tennis', 'Football', 'Basketball'], '5% seats reserved for national level, 3% for state level athletes', 'STATE', ARRAY['Arts', 'Science', 'Commerce'], '2026-06-15', 'https://du.ac.in/sports-quota', 'sportsquota@du.ac.in', '+91-11-27001234'),
('Punjab University Sports Department', 'Chandigarh', 'Punjab', true, 40, true, ARRAY['Athletics', 'Hockey', 'Wrestling', 'Kabaddi', 'Gymnastics'], 'Sports quota admission with trail-based selection', 'DISTRICT', ARRAY['Arts', 'Science'], '2026-05-31', 'https://puchd.ac.in/sports', 'sportsdept@puchd.ac.in', '+91-172-2541234'),
('Savitribai Phule Pune University', 'Pune', 'Maharashtra', true, 35, true, ARRAY['Athletics', 'Swimming', 'Badminton', 'Volleyball', 'Kho-Kho'], 'Merit-cum-sports achievement based admission', 'STATE', ARRAY['Arts', 'Science', 'Commerce'], '2026-06-20', 'https://unipune.ac.in/sports', 'sportsquota@unipune.ac.in', '+91-20-25601234'),
('Anna University Sports Academy', 'Chennai', 'Tamil Nadu', true, 45, true, ARRAY['Athletics', 'Badminton', 'Basketball', 'Table Tennis', 'Swimming'], 'Engineering admission sports quota for state/national players', 'STATE', ARRAY['Engineering', 'Technology'], '2026-05-15', 'https://annauniv.edu/sports', 'sportsacademy@annauniv.edu', '+91-44-22351234'),
('Banaras Hindu University', 'Varanasi', 'Uttar Pradesh', true, 30, true, ARRAY['Athletics', 'Wrestling', 'Boxing', 'Kabaddi', 'Archery'], 'Sports quota admission through sports trial and certificate verification', 'DISTRICT', ARRAY['Arts', 'Science', 'Commerce'], '2026-04-30', 'https://bhu.ac.in/sports-quota', 'sports@bhu.ac.in', '+91-542-2361234'),
('University of Kerala Sports Dept', 'Thiruvananthapuram', 'Kerala', true, 35, false, ARRAY['Athletics', 'Football', 'Volleyball', 'Badminton', 'Swimming'], 'Weightage for sports achievement in admission', 'DISTRICT', ARRAY['Arts', 'Science'], '2026-05-20', 'https://keralauniversity.ac.in/sports', 'sportsquota@keralauniversity.ac.in', '+91-471-2301234'),
('Bangalore University Sports Complex', 'Bangalore', 'Karnataka', true, 40, true, ARRAY['Athletics', 'Badminton', 'Cricket', 'Football', 'Hockey'], 'Direct admission for national level achievers', 'STATE', ARRAY['Arts', 'Science', 'Commerce'], '2026-06-01', 'https://bangaloreuniversity.ac.in/sports', 'sportsdept@bub.ernet.in', '+91-80-22961234'),
('GNDU Sports Department', 'Amritsar', 'Punjab', true, 50, true, ARRAY['Athletics', 'Wrestling', 'Kabaddi', 'Hockey', 'Boxing'], 'Excellent sports infrastructure with direct admission', 'STATE', ARRAY['Arts', 'Science', 'Physical Education'], '2026-05-25', 'https://gndu.ac.in/sports', 'sportsquota@gndu.ac.in', '+91-183-2251234'),
('Mumbai University Sports Cell', 'Mumbai', 'Maharashtra', true, 45, true, ARRAY['Athletics', 'Swimming', 'Badminton', 'Table Tennis', 'Carrom'], 'Sports quota seats with priority to national winners', 'STATE', ARRAY['Arts', 'Science', 'Commerce'], '2026-06-10', 'https://mu.ac.in/sports', 'sports.cell@mu.ac.in', '+91-22-26541234'),
('Lakshmibai National University', 'Gwalior', 'Madhya Pradesh', true, 60, true, ARRAY['Athletics', 'Wrestling', 'Boxing', 'Kabaddi', 'Hockey', 'Badminton'], 'Sports specialized university - direct admission for achievers', 'STATE', ARRAY['Physical Education', 'Sports Science'], '2026-04-20', 'https://lnipe.nic.in', 'admission@lnipe.nic.in', '+91-751-2401234');

-- Insert Opportunities
INSERT INTO opportunities (title, type, organization, location, state, deadline, event_date, description, sport, women_focused, age_min, age_max, registration_url, contact_email, contact_phone) VALUES
('Khelo India Women''s Kabaddi League', 'TOURNAMENT', 'Amateur Kabaddi Federation of India', 'Hisar', 'Haryana', '2026-02-15', '2026-03-01', 'National level tournament for women kabaddi players. Winners get direct selection for national camp.', 'Kabaddi', true, 16, 28, 'https://akhindia.org/womens-league', 'kabaddiwoman@afi.org', '+91-11-24361234'),
('National Women''s Athletics Championship', 'TOURNAMENT', 'Athletics Federation of India', 'Bengaluru', 'Karnataka', '2026-02-28', '2026-03-15', 'Annual championship with qualification for Asian Games trials. Events: 100m, 200m, 400m, 800m, long jump, discus throw.', 'Athletics', true, 14, 30, 'https://afi.org.in/national-womens-championship', 'womensathletics@afi.org', '+91-80-23411234'),
('SAI Sports Excellence Camp', 'CAMP', 'Sports Authority of India', 'Multiple Locations', NULL, '2026-03-01', '2026-04-15', '45-day intensive training camp at SAI centers. For U-18 athletes in athletics, badminton, and wrestling.', NULL, true, 12, 18, 'https://sportsauthorityofindia.gov.in/excellence-camp', 'excellence@sai.gov.in', '+91-11-26811234'),
('Women''s Cricket U-19 Selection Trials', 'TRIAL', 'BCCI', 'Delhi', 'Delhi', '2026-01-30', '2026-02-10', 'Selection trials for India U-19 women''s cricket team. Open to registered players with state achievement.', 'Cricket', true, 15, 19, 'https://bcci.tv/womens-u19-trials', 'womencricket@bcci.tv', '+91-22-22851234'),
('BWF Badminton Academy Program', 'ACADEMY', 'Badminton Association of India', 'Hyderabad', 'Telangana', '2026-02-20', '2026-06-01', '4-month residential program at Pullela Gopichand Academy. Selection based on state level achievement.', 'Badminton', true, 11, 17, 'https://badminmintonindia.org/academy-program', 'academy@bai.org.in', '+91-40-23451234'),
('Khelo India Girl Athlete Talent Hunt', 'TRIAL', 'Khelo India Programme', 'Lucknow', 'Uttar Pradesh', '2026-03-10', '2026-03-20', 'Identifying talented rural girl athletes for Khelo India scholarship. Sports: Athletics, Wrestling, Boxing.', NULL, true, 10, 16, 'https://kheloindia.gov.in/talent-hunt-lucknow', 'talenthunt@kheloindia.gov.in', '+91-522-22341234'),
('Women''s Wrestling National Championship', 'TOURNAMENT', 'Wrestling Federation of India', 'Patna', 'Bihar', '2026-02-25', '2026-03-08', 'National championship for women in all weight categories. Pathway to world championship trials.', 'Wrestling', true, 16, 25, 'https://wfi.org.in/womens-championship', 'womenwrestling@wfi.org', '+91-11-23411234'),
('Rural Girls Hockey Development Program', 'CAMP', 'Hockey India', 'Ranchi', 'Jharkhand', '2026-03-05', '2026-04-30', 'Free 2-month training camp for rural girls. Equipment and accommodation provided.', 'Hockey', true, 12, 18, 'https://hockeyindia.org/rural-development', 'devprogram@hockeyindia.org', '+91-11-45671234'),
('BCCI Women''s T20 Challenge', 'TOURNAMENT', 'BCCI', 'Mumbai', 'Maharashtra', '2026-04-15', '2026-05-01', 'Professional T20 tournament with opportunities to play alongside international players.', 'Cricket', true, 16, 28, 'https://bcci.tv/womens-challenge', 't20women@bcci.tv', '+91-22-22851234'),
('Madhya Pradesh Government Sports Scheme', 'GOVERNMENT_SCHEME', 'MP Sports Department', 'Bhopal', 'Madhya Pradesh', '2026-04-30', NULL, 'Monthly stipend and training support for female athletes in indigenous sports.', NULL, true, 12, 25, 'https://mpsports.gov.in/sports-scheme', 'sportsdept@mp.gov.in', '+91-755-2741234'),
('National Kho-Kho Women''s League', 'TOURNAMENT', 'Kho-Kho Federation of India', 'Bhuvneshwar', 'Odisha', '2026-03-25', '2026-04-05', 'League format tournament for women kho-kho teams. Cash prizes for winning teams.', 'Kho-Kho', true, 16, 26, 'https://khokhoindia.org/womens-league', 'league@kkfi.org', '+91-11-25891234'),
('Tamil Nadu Sports Academy Trial', 'TRIAL', 'Tamil Nadu Sports Development Authority', 'Chennai', 'Tamil Nadu', '2026-02-10', '2026-02-25', 'Selection trials for SDAT sports academy. Sports: Athletics, Swimming, Table Tennis.', NULL, true, 12, 20, 'https://sdat.tn.gov.in/academy-trials', 'academy@sdat.tn.gov.in', '+91-44-23451234');

-- Insert Training Resources
INSERT INTO training_resources (title, category, content_type, content, video_url, author, duration_minutes, is_published, sport, tags) VALUES
('Beginner''s Guide to Athletics Training', 'Training Basics', 'GUIDE', 'Complete guide covering warm-up, technique drills, and cool-down for young athletes. Includes nutrition advice and recovery tips.', NULL, 'Coach Ramesh Kumar', 45, true, 'Athletics', ARRAY['beginner', 'warm-up', 'technique', 'nutrition']),
('Mental Strength for Athletes', 'Mental Health', 'ARTICLE', 'Understanding the importance of mental health in sports performance. Tips on handling pressure, staying motivated, and dealing with setbacks.', NULL, 'Dr. Priya Sharma', 20, true, NULL, ARRAY['mental health', 'motivation', 'pressure']),
('Nutrition Guide for Female Athletes', 'Nutrition', 'ARTICLE', 'Essential nutrition advice for girl athletes including iron requirements, protein intake, and maintaining energy balance during training.', NULL, 'Dr. Anjali Rao', 25, true, NULL, ARRAY['nutrition', 'iron', 'protein', 'energy']),
('Kabaddi Training Drills - Video Series', 'Training Basics', 'VIDEO', 'Step-by-step video tutorials for kabaddi skills including raiding technique, defending positions, and conditioning exercises.', 'https://training.shakthi.org/kabaddi-drills', 'Coach Sunil Kumar', 60, true, 'Kabaddi', ARRAY['kabaddi', 'raiding', 'defending', 'drills']),
('Injury Prevention Exercises', 'Exercise', 'EXERCISE', 'Daily routine of 15 exercises to prevent common sports injuries. Focus on knees, ankles, and shoulders.', NULL, 'Physio Arun Patel', 30, true, NULL, ARRAY['injury prevention', 'mobility', 'strength']),
('Yoga for Flexibility', 'Exercise', 'VIDEO', '10-minute yoga routine specifically designed for athletes. Improves flexibility and mental focus.', 'https://training.shakthi.org/yoga-flexibility', 'Yoga Instructor Meena Devi', 10, true, NULL, ARRAY['yoga', 'flexibility', 'mindfulness']),
('Badminton Grip and Stroke Basics', 'Training Basics', 'VIDEO', 'Master the fundamental grips and strokes in badminton. Beginner-friendly tutorial.', 'https://training.shakthi.org/badminton-basics', 'Coach Rajesh Singh', 35, true, 'Badminton', ARRAY['badminton', 'grip', 'stroke', 'beginner']),
('Wrestling Diet and Weight Management', 'Nutrition', 'ARTICLE', 'Safe weight management strategies for wrestlers. Importance of hydration and timing of meals.', NULL, 'Sports Nutritionist Kavita', 15, true, 'Wrestling', ARRAY['wrestling', 'diet', 'weight', 'nutrition']),
('Hockey Skills: Dribbling and Passing', 'Training Basics', 'VIDEO', 'Learn essential hockey dribbling techniques and passing drills for team play.', 'https://training.shakthi.org/hockey-skills', 'Coach Harpreet Singh', 40, true, 'Hockey', ARRAY['hockey', 'dribbling', 'passing', 'skills']),
('Recovery and Rest for Young Athletes', 'Mental Health', 'ARTICLE', 'Understanding the importance of rest days and recovery. Signs of overtraining and when to take a break.', NULL, 'Dr. Sunita Verma', 20, true, NULL, ARRAY['recovery', 'rest', 'overtraining', 'health']),
('Cricket Batting Techniques for Women', 'Training Basics', 'VIDEO', 'Master cover drives, pull shots, and defensive techniques. Specifically designed for women cricketers.', 'https://training.shakthi.org/cricket-batting', 'Coach Mithali Raj Academy', 50, true, 'Cricket', ARRAY['cricket', 'batting', 'technique', 'women']),
('Strength Training Without Gym', 'Exercise', 'VIDEO', 'Bodyweight exercises for building strength at home. No equipment needed.', 'https://training.shakthi.org/strength-home', 'Fitness Trainer Anita', 25, true, NULL, ARRAY['strength', 'home workout', 'bodyweight']),
('Kho-Kho Game Rules and Strategies', 'Training Basics', 'GUIDE', 'Complete rulebook and advanced strategies for kho-kho players and coaches.', NULL, 'KKFI Technical Committee', 30, true, 'Kho-Kho', ARRAY['kho-kho', 'rules', 'strategy', 'tactics']),
('Building Confidence in Sports', 'Mental Health', 'ARTICLE', 'Practical tips for building self-confidence as an athlete. Managing fearlessness vs anxiety.', NULL, 'Sports Psychologist Dr. Kaur', 15, true, NULL, ARRAY['confidence', 'mental health', 'anxiety']),
('Pre-Competition Routine Guide', 'Training Basics', 'ARTICLE', 'How to prepare mentally and physically before a competition. Night-before and morning-of routines.', NULL, 'Coach Sunil Kumar', 10, true, NULL, ARRAY['competition', 'routine', 'preparation', 'tips']);

-- Insert Admin user (password: admin123 - should be changed immediately)
-- Note: In production, this would be handled through Supabase Auth